development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:49ee12bfbab3f90d7cc6cde7b1c04664@dory.redistogo.com:9827/
  channel_prefix: instatalk_production
  